version: "3.8"
services:
  # nginx_tpl:
  #   image: nginx
  #   volumes:
  #     - '../../nginx/default.conf:/etc/nginx/nginx.conf'
  #     - '../../nginx/ssl:/etc/nginx/ssl'
  #   ports:
  #     - '8888:80' #local:docker
  #     - '554:443'
  #   depends_on:
  #     - tpl


  #django app
  tpl:
    image: python:3.7
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      make deps
      make migrate
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:8000
      '
    ports:
      - "8000:8000"
  