# Generated by Django 3.2.18 on 2023-03-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_rename_stuffing_sku_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='stuff',
        ),
    ]
