# Generated by Django 3.2.18 on 2023-03-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0006_tyre_stuff'),
        ('process', '0003_remove_sku_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='stuff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='tyre.stuff'),
        ),
    ]
