# Generated by Django 3.2.18 on 2023-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0007_auto_20230307_1318'),
        ('process', '0004_sku_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='payment_basis',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_basis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='tyre.paymentbasis'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='stuff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='tyre.stufftype'),
        ),
        migrations.AddField(
            model_name='sku',
            name='number_of_containers',
            field=models.FloatField(null=True),
        ),
    ]
