# Generated by Django 3.2.18 on 2023-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20230307_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sku',
            name='number_of_containers',
            field=models.FloatField(null=True, verbose_name='No. of containers'),
        ),
        migrations.CreateModel(
            name='QuotationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_summary', to='process.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
