# Generated by Django 3.2.18 on 2023-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20230307_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
