# Generated by Django 3.2.18 on 2023-03-07 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0007_auto_20230307_1318'),
        ('customer', '0001_initial'),
        ('process', '0008_quotation_quote_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='is_past',
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='quotation_summary', to='process.currency'),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_summary', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='exchange_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='payment_basis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_summary', to='tyre.paymentbasis'),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='quote_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='stuff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_summary', to='tyre.stufftype'),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationsummary',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SKUSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('number_of_containers', models.FloatField(null=True, verbose_name='No. of containers')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.brand')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.pattern')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.pr')),
                ('quotation_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='process.quotationsummary')),
                ('stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.stuff')),
                ('tyre_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.tyreset')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='tyre.tyresize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
