# Generated by Django 3.2.18 on 2023-03-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_auto_20230307_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='skusummary',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_summary', to='process.sku'),
        ),
    ]
