# Generated by Django 3.2.18 on 2023-03-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('process', '0011_auto_20230308_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoice',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='customer.country'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='from_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_performa_invoice', to='process.location'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='packing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.packingtype'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.paymentterms'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='pi_remarks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.piremarks'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='sender_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.senderaddress'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='shipping_marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.shippingmarks'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='to_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_performa_invoice', to='process.location'),
        ),
    ]
