# Generated by Django 3.2.18 on 2023-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_auto_20230308_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoice',
            name='pi_date',
            field=models.DateField(null=True),
        ),
    ]
