# Generated by Django 3.2.18 on 2023-03-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_historicalquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='process.performainvoice'),
        ),
        migrations.DeleteModel(
            name='HistoricalQuotation',
        ),
    ]
