# Generated by Django 3.2.18 on 2023-03-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_purchaseorder_pi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='sender_address',
            new_name='receiving_address',
        ),
    ]
