# Generated by Django 3.2.18 on 2023-03-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import process.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0008_stuffmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_auto_20230308_1529'),
        ('process', '0018_rename_sender_address_purchaseorder_receiving_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cs_number', models.CharField(blank=True, default=process.models.get_po_number, max_length=60, null=True)),
                ('co_date', models.DateField()),
                ('freight_cost', models.FloatField(null=True)),
                ('insurance_cost', models.FloatField(null=True)),
                ('dcp_cost', models.FloatField(null=True)),
                ('advt_cost_percent', models.FloatField(null=True)),
                ('sales_contract_number', models.CharField(max_length=30)),
                ('expected_deliver_date', models.DateField(null=True)),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='customer.customer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.senderaddress')),
                ('container_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='tyre.containertype')),
                ('discharge_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_cost_sheet', to='process.location')),
                ('final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_cost_sheet', to='process.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LCTTInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasePayTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseordersku',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_sku', to='tyre.containertype'),
        ),
        migrations.AddField(
            model_name='sku',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='tyre.containertype'),
        ),
        migrations.AlterField(
            model_name='purchaseordersku',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_sku', to='tyre.stuffmaster'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tyre.stuffmaster'),
        ),
        migrations.CreateModel(
            name='CostSheetSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('number_of_containers', models.FloatField(blank=True, null=True, verbose_name='No. of containers')),
                ('discount', models.FloatField(null=True)),
                ('dcp', models.FloatField(null=True)),
                ('sales_manager_commission', models.FloatField(null=True)),
                ('vip', models.FloatField(null=True)),
                ('advt', models.FloatField(null=True)),
                ('net_fob', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.brand')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='process.costsheet')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.containertype')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.pattern')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.pr')),
                ('stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.stuffmaster')),
                ('tyre_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.tyreset')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_sku', to='tyre.tyresize')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='costsheet',
            name='inspection_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.inspectioninstruction'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='lc_tt_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.lcttinstruction'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='packaging_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.packaginginstruction'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='payment_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.paymentterms'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='price_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.priceterms'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='purchase_pay_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.purchasepayterms'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='customer.region'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='sales_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager_cost_sheet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='special_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.specialinstruction'),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='process.status'),
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('commison_percent', models.FloatField(blank=True, default=0, null=True)),
                ('commison_value', models.FloatField(blank=True, default=0, null=True)),
                ('cost_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.costsheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
