# Generated by Django 3.2.18 on 2023-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20230308_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costsheetsku',
            old_name='stuff',
            new_name='stuffing',
        ),
        migrations.RenameField(
            model_name='purchaseordersku',
            old_name='stuff',
            new_name='stuffing',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='stuff',
            new_name='stuffing',
        ),
    ]
