# Generated by Django 3.2.18 on 2023-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0020_auto_20230308_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='stuff_type',
        ),
    ]
