# Generated by Django 3.2.18 on 2023-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0021_remove_quotation_stuff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordersku',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
