# Generated by Django 3.2.18 on 2023-03-10 15:45

from django.db import migrations, models
import django.db.models.deletion
import process.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230308_1529'),
        ('tyre', '0008_stuffmaster'),
        ('supplier', '0004_auto_20230307_1556'),
        ('process', '0023_auto_20230310_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spi_number', models.CharField(blank=True, default=process.models.get_spi_number, max_length=60, null=True)),
                ('spi_date', models.DateField(null=True)),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='customer.country')),
                ('from_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi_from', to='process.location')),
                ('packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.packingtype')),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.paymentterms')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.purchaseorder')),
                ('po_remarks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.poremarks')),
                ('receiving_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.senderaddress')),
                ('shipping_marks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.shippingmarks')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='supplier.supplier')),
                ('to_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi_to', to='process.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformaInvoiceSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('number_of_containers', models.FloatField(blank=True, null=True, verbose_name='No. of containers')),
                ('price', models.FloatField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.brand')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.containertype')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.pattern')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.pr')),
                ('spi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='process.supplierperformainvoice')),
                ('stuffing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.stuffmaster')),
                ('tyre_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.tyreset')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_sku', to='tyre.tyresize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
