# Generated by Django 3.2.18 on 2023-03-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0024_supplierperformainvoice_supplierperformainvoicesku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierperformainvoice',
            old_name='po_remarks',
            new_name='spo_remarks',
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='cost_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoice', to='process.costsheet'),
        ),
        migrations.AddField(
            model_name='supplierperformainvoice',
            name='cost_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='process.costsheet'),
        ),
    ]
