# Generated by Django 3.2.18 on 2023-03-11 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230308_1529'),
        ('process', '0026_auto_20230310_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bl_number', models.CharField(max_length=20)),
                ('bl_image', models.ImageField(upload_to='')),
                ('insuarance_number', models.CharField(max_length=20)),
                ('insuarance_image', models.ImageField(upload_to='')),
                ('supplier_invoice_number', models.CharField(max_length=20)),
                ('supplier_invoice_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=60, null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.bl')),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='customer.country')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='customer.customer')),
                ('from_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_customer_invoice', to='process.location')),
                ('invoice_remarks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.piremarks')),
                ('packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.packingtype')),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.paymentterms')),
                ('sender_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.senderaddress')),
                ('shipping_marks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.shippingmarks')),
                ('to_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_customer_invoice', to='process.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
