# Generated by Django 3.2.18 on 2023-03-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0027_bl_customerinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bl',
            old_name='insuarance_image',
            new_name='supplier_insuarance_image',
        ),
        migrations.RenameField(
            model_name='bl',
            old_name='insuarance_number',
            new_name='supplier_insuarance_number',
        ),
        migrations.RenameField(
            model_name='costsheet',
            old_name='advt_cost_percent',
            new_name='freight_purchae',
        ),
        migrations.RenameField(
            model_name='costsheet',
            old_name='dcp_cost',
            new_name='insurance_purchase',
        ),
        migrations.RenameField(
            model_name='costsheet',
            old_name='freight_cost',
            new_name='total_advt_percentage',
        ),
        migrations.RenameField(
            model_name='costsheet',
            old_name='insurance_cost',
            new_name='total_discount',
        ),
    ]
