# Generated by Django 3.2.18 on 2023-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0029_auto_20230311_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheet',
            name='total_vip_percentage',
            field=models.FloatField(null=True),
        ),
    ]
