# Generated by Django 3.2.18 on 2023-03-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0031_auto_20230311_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costsheet',
            old_name='total_discount',
            new_name='total_discount_percentage',
        ),
        migrations.AddField(
            model_name='costsheet',
            name='net_fob',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='costsheet',
            name='net_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='costsheetsku',
            name='agents_commison',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='cost_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_comms', to='process.costsheet'),
        ),
    ]
