# Generated by Django 3.2.18 on 2023-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0033_auto_20230311_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheet',
            name='sales_manager_commission',
            field=models.FloatField(default=0, null=True),
        ),
    ]
