# Generated by Django 3.2.18 on 2023-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0008_stuffmaster'),
        ('process', '0034_costsheet_sales_manager_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bl',
            name='bl_image',
        ),
        migrations.RemoveField(
            model_name='bl',
            name='supplier_insuarance_image',
        ),
        migrations.RemoveField(
            model_name='bl',
            name='supplier_invoice_image',
        ),
        migrations.AddField(
            model_name='bl',
            name='bl_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bl',
            name='cost_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl', to='process.costsheet'),
        ),
        migrations.AddField(
            model_name='bl',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bl',
            name='freight_invoice_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bl',
            name='freight_invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bl',
            name='insuarance_invoice_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bl',
            name='insuarance_invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bl',
            name='shipped_on_board',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bl',
            name='shipping_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bl',
            name='supplier_insuarance_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bl',
            name='supplier_invoice_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bl',
            name='bl_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bl',
            name='supplier_insuarance_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bl',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ContainerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('bl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='process.bl')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='tyre.brand')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='tyre.pattern')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='tyre.pr')),
                ('tyre_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='tyre.tyreset')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_sku', to='tyre.tyresize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
