# Generated by Django 3.2.18 on 2023-03-11 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230308_1529'),
        ('process', '0038_rename_bl_containerbox_box_bl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='consignee',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='country_final_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_customer_invoice', to='customer.country'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='final_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_customer_invoice', to='process.location'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='port_of_discharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_customer_invoice', to='process.location'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='receipt_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_customer_invoice', to='customer.country'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='vessel_flight_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='ci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='process.customerinvoice'),
        ),
        migrations.CreateModel(
            name='PackagingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.TextField(null=True)),
                ('pl_number', models.CharField(blank=True, max_length=60, null=True)),
                ('vessel_flight_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(null=True)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.bl')),
                ('country_final_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_packaging_list', to='customer.country')),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='customer.country')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='customer.customer')),
                ('delivery_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.deliveryterm')),
                ('final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_packaging_list', to='process.location')),
                ('from_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_packaging_list', to='process.location')),
                ('invoice_remarks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.piremarks')),
                ('packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.packingtype')),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.paymentterms')),
                ('port_of_discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_packaging_list', to='process.location')),
                ('receipt_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_packaging_list', to='customer.country')),
                ('sender_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.senderaddress')),
                ('shipment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.shipmentmode')),
                ('shipping_marks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_list', to='process.shippingmarks')),
                ('to_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_packaging_list', to='process.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='delivery_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.deliveryterm'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='shipment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='process.shipmentmode'),
        ),
        migrations.AddField(
            model_name='sku',
            name='pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='process.packaginglist'),
        ),
    ]
