# Generated by Django 3.2.18 on 2023-03-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0039_auto_20230311_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerbox',
            name='customer_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_box', to='process.customerinvoice'),
        ),
        migrations.AddField(
            model_name='containersku',
            name='customer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='containersku',
            name='supplier_price',
            field=models.FloatField(default=0),
        ),
    ]
