# Generated by Django 3.2.18 on 2023-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0042_rename_packging_list_containerbox_customer_packging_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='containersku',
            name='customer_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='containersku',
            name='supplier_amount',
            field=models.FloatField(default=0),
        ),
    ]
