# Generated by Django 3.2.18 on 2023-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0043_auto_20230311_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl',
            name='total_supplier_invoice_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='total_customer_invoice_amount',
            field=models.FloatField(default=0),
        ),
    ]
