# Generated by Django 3.2.18 on 2023-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0044_auto_20230311_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bl',
            name='shipped_on_board',
        ),
        migrations.AddField(
            model_name='bl',
            name='shipped_on_date',
            field=models.DateField(null=True),
        ),
    ]
