# Generated by Django 3.2.18 on 2023-03-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0045_auto_20230311_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='payment_basis',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='process.paymentterms'),
        ),
    ]
