# Generated by Django 3.2.18 on 2023-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0046_auto_20230311_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancett',
            name='advance_percentage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balanceterm',
            name='term',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dayseta',
            name='eta',
            field=models.CharField(max_length=50),
        ),
    ]
