# Generated by Django 3.2.18 on 2023-03-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230308_1529'),
        ('process', '0049_quotation_price_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='customer.country'),
        ),
    ]
