# Generated by Django 3.2.18 on 2023-03-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0051_auto_20230311_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl',
            name='shipment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl', to='process.shipmentmode'),
        ),
        migrations.AddField(
            model_name='bl',
            name='vessel_flight_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
