# Generated by Django 3.2.18 on 2023-03-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0002_remove_tyre_stuffing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='stuffing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre', to='tyre.stuffing'),
        ),
    ]
