# Generated by Django 3.2.18 on 2023-03-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_remove_sku_stuff'),
        ('tyre', '0003_tyre_stuffing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='stuffing',
        ),
        migrations.DeleteModel(
            name='Stuffing',
        ),
    ]
