# Generated by Django 3.2.18 on 2023-03-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0008_stuffmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffmaster',
            name='stuff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff_master', to='tyre.stufftype'),
        ),
    ]
