# Generated by Django 3.2.18 on 2023-03-07 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0007_auto_20230307_1318'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('number_of_containers', models.FloatField(null=True, verbose_name='No. of containers')),
                ('cost', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.brand')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.pattern')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.pr')),
                ('stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.stuff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='supplier.supplier')),
                ('tyre_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.tyreset')),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku', to='tyre.tyresize')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierSKUSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sku_summary', to='supplier.suppliersku')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
